---
title: "NSSE 2022 and Historical Analysis [In Progress]"
author: "Amy N. Warnock"
date: "2022-12-03"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      fig.width = 8,
                      fig.height = 6)

#install.packages("here")
#install.packages("tidyverse")
#install.packages("janitor")
#install.packages("rio")
#install.packages("colorblindr")
#install.packages("scales")
#install.packages("wesanderson")
#install.packages("ggridges")
#install.packages("Rfast")
#install.packages("MASS")
#install.packages("likert")
#install.packages("psych")
#install.packages("haven")
#install.packages("sjPlot")
#install.packages("ggrepel")
#install.packages("cowplot")
#install.packages("remotes")
#remotes::install_github("martinctc/surveytoolbox")
#install.packages("colorspace", repos = "http://R-Forge.R-project.org")
#remotes::install_github("clauswilke/colorblindr")
#install.packages("stringr")
#install.packages("gt")
#install.packages("gtExtras")
#install.packages("ggh4x")

library(here)
library(tidyverse)
library(janitor)
library(rio)
library(scales)
library(wesanderson)
library(likert)
library(ggrepel)
library(cowplot)
library(surveytoolbox)
library(colorblindr)
library(stringr)
library(gt)
library(gtExtras)
library(ggh4x)
library(psych)

#library(sjPlot)
```

```{r load-wrangle-historical-nsse}

# load historical NSSE files, selecting only vars of interest

nsse03 <- import(
  here("data", "NSSE03 Data (UO).sav"), 
  setclass = "tbl_df") %>% 
  select(studid,
         classran,
         class,
         cocurr01,
         workof01,
         workon01) %>% 
  mutate(year = "2003",
         studid = as.numeric(studid),
         tmworkonhrs =
           case_when(
             workon01 == '1' ~ 0,
             workon01 == '2' ~ 3,
             workon01 == '3' ~ 8,
             workon01 == '4' ~ 13,
             workon01 == '5' ~ 18,
             workon01 == '6' ~ 23,
             workon01 == '7' ~ 28,
             workon01 == '8' ~ 33),
         tmworkoffhrs =
           case_when(
             workof01 == '1' ~ 0,
             workof01 == '2' ~ 3,
             workof01 == '3' ~ 8,
             workof01 == '4' ~ 13,
             workof01 == '5' ~ 18,
             workof01 == '6' ~ 23,
             workof01 == '7' ~ 28,
             workof01 == '8' ~ 33),
         tmworkhrs = tmworkonhrs + tmworkoffhrs) %>% 
  rename(IRclass = classran,
         studentid = studid,
         tmcocurr = cocurr01)

nsse06 <- import(
  here("data", "NSSE06 Data (UO).sav"), 
  setclass = "tbl_df") %>% 
  select(studid,
         classran,
         class,
         cocurr01,
         workof01,
         workon01) %>% 
  mutate(year = "2006",
         studid = as.numeric(studid),
         tmworkonhrs =
           case_when(
             workon01 == '1' ~ 0,
             workon01 == '2' ~ 3,
             workon01 == '3' ~ 8,
             workon01 == '4' ~ 13,
             workon01 == '5' ~ 18,
             workon01 == '6' ~ 23,
             workon01 == '7' ~ 28,
             workon01 == '8' ~ 33),
         tmworkoffhrs =
           case_when(
             workof01 == '1' ~ 0,
             workof01 == '2' ~ 3,
             workof01 == '3' ~ 8,
             workof01 == '4' ~ 13,
             workof01 == '5' ~ 18,
             workof01 == '6' ~ 23,
             workof01 == '7' ~ 28,
             workof01 == '8' ~ 33),
         tmworkhrs = tmworkonhrs + tmworkoffhrs) %>% 
  rename(IRclass = classran,
         studentid = studid,
         tmcocurr = cocurr01)

nsse09 <- import(
  here("data", "NSSE09 Data (UO).sav"), 
  setclass = "tbl_df") %>% 
  select(studid,
         classran,
         class,
         cocurr01,
         workof01,
         workon01) %>% 
  mutate(year = "2009",
         studid = as.numeric(studid),
         tmworkonhrs =
           case_when(
             workon01 == '1' ~ 0,
             workon01 == '2' ~ 3,
             workon01 == '3' ~ 8,
             workon01 == '4' ~ 13,
             workon01 == '5' ~ 18,
             workon01 == '6' ~ 23,
             workon01 == '7' ~ 28,
             workon01 == '8' ~ 33),
         tmworkoffhrs =
           case_when(
             workof01 == '1' ~ 0,
             workof01 == '2' ~ 3,
             workof01 == '3' ~ 8,
             workof01 == '4' ~ 13,
             workof01 == '5' ~ 18,
             workof01 == '6' ~ 23,
             workof01 == '7' ~ 28,
             workof01 == '8' ~ 33),
         tmworkhrs = tmworkonhrs + tmworkoffhrs) %>% 
  rename(IRclass = classran,
         studentid = studid,
         tmcocurr = cocurr01)

nsse12 <- import(
  here("data", "NSSE12 Data (UO).sav"), 
  setclass = "tbl_df") %>% 
  select(studid,
         classran,
         class,
         cocurr01,
         workof01,
         workon01) %>% 
  mutate(year = "2012",
         studid = as.numeric(studid),
         tmworkonhrs =
           case_when(
             workon01 == '1' ~ 0,
             workon01 == '2' ~ 3,
             workon01 == '3' ~ 8,
             workon01 == '4' ~ 13,
             workon01 == '5' ~ 18,
             workon01 == '6' ~ 23,
             workon01 == '7' ~ 28,
             workon01 == '8' ~ 33),
         tmworkoffhrs =
           case_when(
             workof01 == '1' ~ 0,
             workof01 == '2' ~ 3,
             workof01 == '3' ~ 8,
             workof01 == '4' ~ 13,
             workof01 == '5' ~ 18,
             workof01 == '6' ~ 23,
             workof01 == '7' ~ 28,
             workof01 == '8' ~ 33),
         tmworkhrs = tmworkonhrs + tmworkoffhrs) %>% 
  rename(IRclass = classran,
         studentid = studid,
         tmcocurr = cocurr01)

nsse15 <- import(
  here("data", "NSSE15 Data (UO).sav"), 
  setclass = "tbl_df") %>% 
  select(studentID,
         IRclass,
         class,
         tmcocurr,
         tmworkhrs) %>% 
  mutate(year = "2015",
         studentID = as.numeric(studentID)) %>% 
  rename(studentid = studentID)

nsse17 <- import(
  here("data", "NSSE17 Data (UO).sav"), 
  setclass = "tbl_df") %>% 
  select(studentID,
         IRclass,
         class,
         tmcocurr,
         tmworkhrs) %>% 
  mutate(year = "2017",
         studentID = as.numeric(studentID)) %>% 
  rename(studentid = studentID)

nsse19 <- import(
  here("data", "NSSE19 Data (UO).sav"), 
  setclass = "tbl_df") %>% 
  select(studentid,
         IRclass,
         class,
         tmcocurr,
         tmworkhrs) %>% 
  mutate(year = "2019",
         studentid = as.numeric(studentid))

nsse22 <- nsse_orig_full %>% 
  select(studentid,
         IRclass,
         class,
         tmcocurr,
         tmworkhrs) %>% 
mutate(year = "2022",
       studentid = as.numeric(studentid),
       IRclass = as.numeric(IRclass))


## for testing out ftfy vs IRclass var

nsse22a <- nsse_orig_full %>% 
  filter(IRclass == "1") %>% 
  select(studentid,
         IRclass,
         tmcocurr,
         tmworkhrs) %>% 
mutate(year = "2022",
       studentid = as.numeric(studentid),
       IRclass = as.numeric(IRclass))


# trying out filtering by ftfy var instead of class var

nsse22b <- nsse_orig_full %>% 
  filter(IRftfy == "1") %>% 
  select(studentid,
         IRclass,
         tmcocurr,
         tmworkhrs) %>% 
  mutate(year = "2022",
         studentid = as.numeric(studentid),
         IRclass = as.numeric(IRclass))

```

```{r combine-datasets}

nsse_historical <- bind_rows(nsse03, nsse06, nsse09,
                        nsse12, nsse15, nsse17,
                        nsse19, nsse22) %>% 
   mutate(tmcocurr_binned = 
           case_when(
             tmcocurr == '1' | tmcocurr == '2' ~ 'Low', 
             tmcocurr == '3' | tmcocurr == '4' ~ 'Moderate', 
             tmcocurr == '5' | tmcocurr == '6' | 
               tmcocurr == '7' | tmcocurr == '8' ~ 'High'),
          tmworkhrs_binned = cut(tmworkhrs, 
                                breaks = c(-Inf, 1, 11, 21, Inf),
                                labels = c("None", "1-10", "11-20", "More than 20"),
                                right = FALSE)) %>% 
  select(year,
         studentid,
         IRclass,
         class,
         tmcocurr,
         tmcocurr_binned,
         tmworkhrs,
         tmworkhrs_binned) %>% 
  left_join(enr_ret_grad,
            by = c("studentid" = "PIDM"))

nsse_historical_fy <- nsse_historical %>% 
  filter(IRclass == "1")

nsse_historical_fy_class <- nsse_historical %>% 
  filter(class == "1")

```

```{r}
ret_cocurr_total <- nsse_historical_fy %>% 
  group_by(year,
           tmcocurr_binned) %>% 
  summarize(ret_year = "overall",
            n = n()) %>% 
  drop_na(tmcocurr_binned)


# count of FY students w/ responses to tmcocurr by NSSE year filtering by institution-reported class
nsse_historical_fy %>% 
  filter(!is.na(tmcocurr_binned)) %>% 
  group_by(year) %>% 
  summarize(n = n())

# count of FY students w/ responses to tmcocurr by NSSE - filtering by CLASS (self-reported)
nsse_historical %>% 
  filter(!is.na(tmcocurr_binned),
         class == "1") %>% 
  group_by(year) %>% 
  summarize(n = n())

```


```{r plot-retention}

nsse_historical_fy %>% 
  select(studentid,
         year,
         tmcocurr_binned,
         starts_with("ret_")) %>% 
  pivot_longer(cols = starts_with("ret"),
               names_to = "ret_year",
               names_prefix = "ret_fall_term_",
               values_to = "ret") %>% 
  filter(ret == "1") %>% 
  group_by(year,
           tmcocurr_binned,
           ret_year) %>% 
  summarize(n = n()) %>% 
  drop_na(tmcocurr_binned) %>% 
  bind_rows(ret_cocurr_total) %>% 
  pivot_wider(names_from = ret_year,
              values_from = n) %>% 
  mutate(percent_yr2 = (yr2 / overall),
         percent_yr3 = (yr3 / overall),
         percent_yr4 = (yr4 / overall)) %>% 
  select(-(3:6)) %>% 
  pivot_longer(cols = 3:5,
               names_to = "ret_year",
               names_prefix = "percent_",
               values_to = "percent") %>% 
  ggplot(aes(x = ret_year, 
             y = percent, 
             group = tmcocurr_binned,
             color = tmcocurr_binned)) +
  geom_point() +
  geom_line() +
  facet_wrap(~ year)

```


```{r}
# why are there yr3 and yr4 retention values for first-year students who took NSSE in 2022?

nsse_historical_fy %>% 
  select(studentid,
         year,
         tmcocurr_binned,
         starts_with("ret_")) %>% 
  pivot_longer(cols = starts_with("ret"),
               names_to = "ret_year",
               names_prefix = "ret_fall_term_",
               values_to = "ret") %>% 
  filter(ret == "1",
         year == "2022") %>% 
  group_by(tmcocurr_binned,
           ret_year) %>% 
  summarize(n = n())

fy_2022_ret34 <- nsse_historical_fy %>% 
  filter(year == "2022",
         ret_fall_term_yr3 == "1" |
         ret_fall_term_yr4 == "1")


nsse_historical_fy %>% 
  filter(ret_fall_term_yr2 == "1") %>% 
  group_by(year,
           tmcocurr_binned) %>% 
  summarize(n = n())

nsse_orig_full %>% 
  group_by(IRclass,
           IRftfy) %>% 
  summarize(n = n())
```


```{r}
# why don't the ns by year match the previous analyses?

nsse_historical_fy %>% 
    group_by(year,
           tmcocurr_binned) %>% 
  summarize(n = n())

nsse_historical_fy %>% 
    group_by(year,
           tmcocurr_binned) %>% 
  summarize(n = n())

nsse03 %>% 
  group_by(tmcocurr) %>% 
  summarize(n = n()) %>% 
  drop_na(tmcocurr) %>% 
  colSums()




# figured it out? Dayle used "class" var for filtering historical datasets, which is the self-reported variable. Other analyses used IRclass, which is what I've been using

nsse03b <- import(
  here("data", "NSSE03 Data (UO).sav"), 
  setclass = "tbl_df") %>% 
  select(studid,
         class,
         classran,
         cocurr01,
         workof01,
         workon01) %>% 
  mutate(studid = as.numeric(studid)) %>% 
  filter(class == "1") %>% 
  rename(studentid = studid,
         tmcocurr = cocurr01)

nsse03b %>% 
  group_by(tmcocurr) %>% 
  summarize(n = n()) 

nsse03b %>% 
  group_by(tmcocurr) %>% 
  summarize(n = n()) %>% 
  drop_na(tmcocurr) %>% 
  colSums()


nsse03b %>% 
  left_join(enr_ret_grad,
            by = c("studentid" = "PIDM")) %>% 
  select(studentid,
         tmcocurr,
         starts_with("ret_")) %>% 
  pivot_longer(cols = starts_with("ret"),
               names_to = "ret_year",
               names_prefix = "ret_fall_term_",
               values_to = "ret") %>% 
  filter(ret == "1") %>% 
  group_by(tmcocurr,
           ret_year) %>% 
  summarize(n = n()) %>% 
  drop_na(tmcocurr) %>% 
  pivot_wider(names_from = ret_year,
              values_from = n)

```


```{r plot-retention-ftfy2022}

bind_rows(nsse03, nsse06, nsse09,
                        nsse12, nsse15, nsse17,
                        nsse19, nsse22b) %>% 
   mutate(tmcocurr_binned = 
           case_when(
             tmcocurr == '1' | tmcocurr == '2' ~ 'Low', 
             tmcocurr == '3' | tmcocurr == '4' ~ 'Moderate', 
             tmcocurr == '5' | tmcocurr == '6' | 
               tmcocurr == '7' | tmcocurr == '8' ~ 'High'),
          tmworkhrs_binned = cut(tmworkhrs, 
                                breaks = c(-Inf, 1, 11, 21, Inf),
                                labels = c("None", "1-10", "11-20", "More than 20"),
                                right = FALSE)) %>% 
  select(year,
         studentid,
         IRclass,
         tmcocurr,
         tmcocurr_binned,
         tmworkhrs,
         tmworkhrs_binned) %>% 
  left_join(enr_ret_grad,
            by = c("studentid" = "PIDM")) %>% 
   select(studentid,
         year,
         tmcocurr_binned,
         starts_with("ret_")) %>% 
  pivot_longer(cols = starts_with("ret"),
               names_to = "ret_year",
               names_prefix = "ret_fall_term_",
               values_to = "ret") %>% 
  filter(ret == "1") %>% 
  group_by(year,
           tmcocurr_binned,
           ret_year) %>% 
  summarize(n = n()) %>% 
  drop_na(tmcocurr_binned) %>% 
  bind_rows(ret_cocurr_total) %>% 
  pivot_wider(names_from = ret_year,
              values_from = n) %>% 
  mutate(percent_yr2 = (yr2 / overall),
         percent_yr3 = (yr3 / overall),
         percent_yr4 = (yr4 / overall)) %>% 
  select(-(3:6)) %>% 
  pivot_longer(cols = 3:5,
               names_to = "ret_year",
               names_prefix = "percent_",
               values_to = "percent") %>% 
  ggplot(aes(x = ret_year, 
             y = percent, 
             group = tmcocurr_binned, 
             color = tmcocurr_binned)) +
  coord_cartesian(ylim = c(0, 1)) +
  geom_point() +
  geom_line() +
  facet_wrap(~ year)
```

